### ISSUE TITLE
MuhRec - reading projections from filelist

### ISSUE THREAD

**Issue by chiaracarminati** [neutronimaging/imagingsuite#1]
When loading a filelist txt file from the browse button, automatically file index firsts is set to 5000 and last to 0. The program stops responding at this point on my ubuntu. 
Workaround to load the images from file list is to set manually first and last index and then type the name of the filelist in the path, without using the browse button.
After this some exceptions are thrown, with dialogues saying "ReconException during Preview" and "Unknown file extension", and they appear when using the sliders and when previewing the reconstructed slices. However by clicking OK, the reconstruction works and results are correctly displayed.

**Comment by anderskaestner** [comment]
A file analyzer has been implemented. It counts the number of line in the file and sets first and the last line correctly. This will probably not work with a file generated on a different OS. E.g. mac vs windows...
