### ISSUE TITLE
Consider using CMake

### ISSUE THREAD

**Issue by DanNixon** [neutronimaging/imagingsuite#110]
[CMake](https://cmake.org/) can be used to generate both QtCreator projects and Unix Makefiles (as well as several others) and would mean not having to maintain a set of scripts for each target (essentially removing everything in the `build/` directory) or specify environment variables before building.

Starting with non-Qt libs
- [x] kipl
- [x] ImagingAlgorithms
- [x] ModuleConfig
- [x] ReaderCOnfig
- [x] ReconFramework
- [x] StdPreprocModules
- [x] InspectorModules
- [x] StdBackProjectors
- [x] FDKBackProjectors

**Comment by anderskaestner** [comment]
The reason we started using environment variables was that the build system got confused which Qt to use when Anaconda was installed. The variables helped us to select the correct Qt installation. If you have a solution to this problem, I'd be happy hear what you suggest.

**Comment by anderskaestner** [comment]
CMake is now used for the python bindings.

**Comment by anderskaestner** [comment]
Cmake is implemented for the core libraries. GUI is still pending and will be handled with the upgrade to Qt 6.2.

**Comment by anderskaestner** [comment]
MuhRec compiles and runs using cmake in macos
