### ISSUE TITLE
Incompatibility with Linux CentOS

### ISSUE THREAD

**Issue by al5612ki-s** [neutronimaging/imagingsuite#122]
Our institution's local computing centre runs on Linux CentOS and we have been unsuccessful in installing the Muhrec3 software on the platform. Is it compatible? 
I can provide further information about our installation attempts on request.

**Comment by anderskaestner** [comment]
The compiled code may not run on CentOS, but I would guess that it should work to compile on your target platform. The requirements are that you have Qt5.9 or higher and a C++ compiler that supports C++11. Take a look at https://github.com/neutronimaging/imagingsuite/wiki/Prerequisites-for-building and https://github.com/neutronimaging/imagingsuite/wiki/Build-instructions. I'm looking forward to hearing about your progress.

**Comment by anderskaestner** [comment]
I am working on the CentOS build now and it is foreseen to have the nightly build to produce precompiled CentOS/RedHat packages. See issues #149, #133, and #269.
