### ISSUE TITLE
MuhRec - FDK attenuation coefficients

### ISSUE THREAD

**Issue by chiaracarminati** [neutronimaging/imagingsuite#230]
FDK gives wrong attenuation coefficients, in particular when reconstructing gold sample (NM dataset), attenuation coefficients are around 20, when it should be around 5. Refer to the project BigData/20180628-AMGold

**Comment by chiaracarminati** [comment]
This issue seems to be also related to the number of projections, for example for another dataset with 625 projs, the overestimation of the attenuation coefficients seem to be of a factor of around 2, while for the dataset referred before, where we have 275 projs, the overestimation seem to have a factor 4.

**Comment by anderskaestner** [comment]
Solved
