### ISSUE TITLE
KipTool -  saving fits in conversion tool

### ISSUE THREAD

**Issue by chiaracarminati** [neutronimaging/imagingsuite#271]
When trying to save fits instead of fits in the conversion tool, instead of giving an exception/message the program crashed. Happened on Win10.

**Comment by chiaracarminati** [comment]
I meant sequence fits instead of sequence of fit

**Comment by anderskaestner** [comment]
The problem seems to be solved in the branch for issue #142. It was a (useless) buffer with static size written beyond the bounds.

**Comment by anderskaestner** [comment]
Solved and Merged
