### ISSUE TITLE
Revise the MorphSpotCleanModule

### ISSUE THREAD

**Issue by chiaracarminati** [neutronimaging/imagingsuite#277]
- [x] Implement different threshold functions for the upper and lower limits.
- [x] use separate plots for fill hole and fill peak.
- [x] Revise clean both to do cleaning separately.
- [ ] Possibly implement detection of large regions to avoid suppression of real image features.

**Comment by anderskaestner** [comment]
Work in progress

**Comment by anderskaestner** [comment]
KipTool still needs attention

**Comment by anderskaestner** [comment]
Last part will be handled in issue #287
