### ISSUE TITLE
MuhRec - saving 8-bit TIFF images

### ISSUE THREAD

**Issue by chiaracarminati** [neutronimaging/imagingsuite#3]
Saving as 8-bit TIFF options saves as 16-bit TIFF.

**Comment by anderskaestner** [comment]
Saving 8-bit is not yet implemented in the WriteTIFF function. This explains the resulting 16-bit images.

**Comment by anderskaestner** [comment]
Intermediate solution: remove the option 8-bit

**Comment by chiaracarminati** [comment]
option for saving 8 bit is no longer available

**Comment by anderskaestner** [comment]
Implemented and tested.
