### ISSUE TITLE
golden ratio order

### ISSUE THREAD

**Issue by timonwehmann** [neutronimaging/imagingsuite#303]
The sorting of golden ratio projections doesn't properly work for values around 300+ projections. Index number of first projection is set correctly.

With 233 projections selected the preview turns evenly with every step and the sinogram looks smooth.
<img width="566" alt="233 proj" src="https://user-images.githubusercontent.com/43242772/58540774-55097100-81fa-11e9-874e-d8276da2f316.png">

An increase of the number of projections (up to next fibonacci = 377) leads to a strange turning behaviour: some steps cw, one step ccw, some steps cw, one step ccw,.. this is also visible in the sinograms.

280 projections
<img width="649" alt="280 proj" src="https://user-images.githubusercontent.com/43242772/58540942-b3ceea80-81fa-11e9-9b5e-c8deb6ea7b00.png">

330 projections
<img width="554" alt="330 proj" src="https://user-images.githubusercontent.com/43242772/58540968-bcbfbc00-81fa-11e9-85bb-1690d023800e.png">

377 projections
<img width="632" alt="377 proj" src="https://user-images.githubusercontent.com/43242772/58540987-c517f700-81fa-11e9-81fa-56de2fd91b6f.png">

**Comment by anderskaestner** [comment]
This problem is data related.
