### ISSUE TITLE
MuhRec - Crashing after "Get piercing point"

### ISSUE THREAD

**Issue by TreckZero** [neutronimaging/imagingsuite#308]
Pressing "Get piercing point" for cone beam geometry closes the program.
Termination Signal: Segmentation fault: 11
Does this no matter how many images are used.
Using the 05/23/2019 release.

**Comment by anderskaestner** [comment]
Can you please give me some more feedback? In particular, which OS did you use.

**Comment by TreckZero** [comment]
Issue occurs on Windows 10 and macOS Mojave. 

`Crashed Thread:        0  Dispatch queue: com.apple.main-thread`
`Exception Type:        EXC_BAD_ACCESS (SIGSEGV)`
`Exception Codes:       KERN_INVALID_ADDRESS at 0x00000000000001a0`
`Exception Note:        EXC_CORPSE_NOTIFY`
`Termination Signal:    Segmentation fault: 11`
`Termination Reason:    Namespace SIGNAL, Code 0xb`
`Terminating Process:   exc handler [3471]`
`Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libQtAddons.1.dylib           	0x00000001087dd238 non-virtual thunk to QtAddons::LoggingDialog::Write(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) + 24`
`1   libkipl.1.dylib               	0x000000010869f114 kipl::logging::Logger::WriteMessage(kipl::logging::Logger::LogLevel, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) + 468`
`2   libkipl.1.dylib               	0x000000010869ee35 kipl::logging::Logger::operator()(kipl::logging::Logger::LogLevel, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >) + 325`
`3   www.imagingscience.ch.MuhRec  	0x000000010846eff2 RunGUI(QApplication*) + 2562`
`4   www.imagingscience.ch.MuhRec  	0x000000010846e19c main + 1116`
`5   libdyld.dylib                 	0x00007fff67ec23d5 start + 1`

**Comment by anderskaestner** [comment]
Did you select open beam and dark current images before clicking the PP button? They are needed by the estimator.
I could at least produce a crash that way. Fix is on the way for that behaviour...

**Comment by anderskaestner** [comment]
The issue has been solved and a new version can be downloaded on
https://jenkins.esss.dk/imaging/job/ImagingSuite_Win10/
and
https://jenkins.esss.dk/imaging/job/ImagingSuite_OSX_10.12/
