### ISSUE TITLE
MuhRec - Add multiple core processing

### ISSUE THREAD

**Issue by TreckZero** [neutronimaging/imagingsuite#309]

**Comment by anderskaestner** [comment]
We do already use multithreading in many parts of the code (windows and linux). As you didn't write any specific part of the processing it is hard to make any priorities. Also, which OS are you using.

**Comment by anderskaestner** [comment]
Multithreading is now implemented in Morphspotclean and will be part of the next release. This is one of the most time consuming preprocessing modules. Speed-up approx x5 on 8 cores.

**Comment by anderskaestner** [comment]
Started to work on Wavelet Ring clean issue #391
