### ISSUE TITLE
MuhRec, CLI requires the existance of destination path

### ISSUE THREAD

**Issue by chiaracarminati** [neutronimaging/imagingsuite#339]
When running MuhRec in a loop, remember to prepare the destination path beforehand, to be included in the template scripts for CLI batch processing. ideally, also MuhRec could check if the destination path exists and create it eventually.

- [x] Locate serialization places in the engine
- [x] Implement create_directories with a log message if directory exists
- [x] Test on mac
- [x] Test on windows
- [ ] Test on linux

**Comment by anderskaestner** [comment]
This will help with the check
https://en.cppreference.com/w/cpp/filesystem/is_directory

**Comment by anderskaestner** [comment]
Would be good if we support C++17...
https://en.cppreference.com/w/cpp/filesystem/create_directory
https://en.cppreference.com/w/cpp/filesystem/is_directory

**Comment by anderskaestner** [comment]
https://stackoverflow.com/questions/67273/how-do-you-iterate-through-every-file-directory-recursively-in-standard-c
