### ISSUE TITLE
MuhRec: module dialogs don't open after merging issue123_configfiles

### ISSUE THREAD

**Issue by chiaracarminati** [neutronimaging/imagingsuite#371]
This happened in Linux. 

The logging showed the following warning:
[warning] ModuleChainConfiguratorWidget: Failed to open dialog: A ModuleException was thrown in file ../../imagingsuite/GUI/qt/QtModuleConfigure/ModuleConfigurator.cpp on line 68: 
Failed to load dialog.A ModuleException was thrown in file ../../imagingsuite/GUI/qt/QtModuleConfigure/ModuleConfigurator.cpp on line 184: 
Failed to load /home/carminati_c/git/deploy/muhrec/Frameworks/libStdPreprocModules.soGUI.1.0.0 (Error: /home/carminati_c/git/deploy/muhrec/Frameworks/libStdPreprocModules.soGUI.1.0.0: cannot open shared object file: No such file or directory)

**Comment by chiaracarminati** [comment]
From the warning it seems that the name is not built correctly:
 /home/carminati_c/git/deploy/muhrec/Frameworks/libStdPreprocModules.soGUI.1.0.0

instead of:
 /home/carminati_c/git/deploy/muhrec/Frameworks/libStdPreprocModulesGUI.so.1.0.0

**Comment by anderskaestner** [comment]
The dialogs work on MacOS and Windows. Reducing the troubleshooting to linux.

**Comment by anderskaestner** [comment]
Problem solved and merged with master.
