### ISSUE TITLE
kipl::base::morphology LabelImage crashes on Win

### ISSUE THREAD

**Issue by chiaracarminati** [neutronimaging/imagingsuite#381]
The crash happens in Win when calling the kipl::morphology::LabelImage function.
Possibly this is due to the fact that the regions to be labeled are connected to the borders of the image. 
Attached an example image which causes the crash 

[maskOtsuFilled.zip](https://github.com/neutronimaging/imagingsuite/files/4030075/maskOtsuFilled.zip)

**Comment by anderskaestner** [comment]
Fix implemented and pull request is issued.
