### ISSUE TITLE
Issue with loading projections when files are numbered 1-2-3-[...]-10-11-... instead of 01-02-...

### ISSUE THREAD

**Issue by matteobsu** [neutronimaging/imagingsuite#462]
Hi,

As title says I think there is an issue loading the projection properly when files are indexed as xxxx_1,2,3,[...],10,11,... instead of xxxx_01,02,03,[...],10,11,...

Matteo

**Comment by anderskaestner** [comment]
It should work if you use the mask basename_#.ext instead of basename_##.ext
