### ISSUE TITLE
ProjectionFilterSingle module produces erroneous recon & can't change config

### ISSUE THREAD

**Issue by martinwissink** [neutronimaging/imagingsuite#502]
Using MuhRec 4.2 on Windows 10 Enterprise, reconstruction of example dataset "wood" with only the FullLogNorm module enabled produces expected result with 99% of gray values spanning -0.0192 to 0.2584. Enabling module ProjectonFilterSingle with default settings produces erroneous result with 99% spanning -0.0158 to 0.0205. Testing with other datasets starting from a new configuration produces similar results.

![image](https://user-images.githubusercontent.com/91552968/135118926-a976f0d8-6443-475a-a67a-cbe7c6270ed8.png)
![image](https://user-images.githubusercontent.com/91552968/135118942-bb92acd7-6272-4c0c-af41-3a94605d640e.png)

Additionally, the Config menu for ProjectionFilterSingle appears to be malfunctioning. The wrong filter appears in the parameter list after pressing OK in the Config menu. For example, if "Shepp-Logan" is selected, "Ram-Lak" appears in the UI parameter list. Any changes made through the Config menu result in a failure to build reconstructor with error message "Reconstructor initialization failed with an STL exception: invalid stoul argument". 

![image](https://user-images.githubusercontent.com/91552968/135118981-739866db-ee79-4912-913d-d4b5d3c2220a.png)
![image](https://user-images.githubusercontent.com/91552968/135118989-fb861a3d-3757-4054-8698-10053eb05a80.png)

**Comment by anderskaestner** [comment]
Projectionfilter as separate module is obsolete. The recon filter is now part of the back projector module where you have all parameters.
Alternatively, you have to deactivate filter in the backproj and use the module in the processing chain.
