### ISSUE TITLE
MuhRec - artifacts in reconstruction when not using dose correction

### ISSUE THREAD

**Issue by chiaracarminati** [neutronimaging/imagingsuite#51]
Some circular-ring artifacts appear outside the reconstructed area when setting to false the dose correction in the FullLogNorm module. 
It happened when using data from MCP detector, which in principle is not affected by the dose normalization. Processing pipeline was : FullLogNorm, MorphSpotClean, WaveletRingClean and filtered back projection 
![with_dose](https://user-images.githubusercontent.com/25690104/37083007-6f605932-21ee-11e8-8de0-18f3aeed7280.png)
![without_dose](https://user-images.githubusercontent.com/25690104/37083015-719d0542-21ee-11e8-8176-4addb3d934f9.png)

**Comment by anderskaestner** [comment]
MCP detector doesn't have DC images. This reduces bug search

**Comment by anderskaestner** [comment]
Test data I got had OB twice the intensity than the Projections. Normalisation by dose is required under such conditions.

**Comment by anderskaestner** [comment]
Not an issue
