### ISSUE TITLE
Troubles reading tiff in muhrec

### ISSUE THREAD

**Issue by anderskaestner** [neutronimaging/imagingsuite#590]
Dear Dr. Kaestner,

My name is Jinn-Jer Peir. Thanks a lot for providing MuhRec. It is very helpful for the research promotion of neutron image. I recently use it to process the NCT test in my laborotory. But I cannot sucefully use MuhRec to read the tiff files generated by our neutron radiography system. I do not know why? The message is attached as the following

![249102175-9767ddcf-07d2-4999-a885-e5cc392c1fc7](https://github.com/neutronimaging/imagingsuite/assets/11174364/d221a03a-346e-4319-8188-14e8d10d3fc7)

@jjpeir

**Comment by anderskaestner** [comment]
Can you please send an example image to me? An open beam would be sufficient.
This problem is probably solved in a more recent version, see issue #576

**Comment by jjpeir** [comment]
Thank for your prompt response. An open beam is attached.
[OB_0001.zip](https://github.com/neutronimaging/imagingsuite/files/11880943/OB_0001.zip)

**Comment by anderskaestner** [comment]
I will not be able to look into it straight away.

Meanwhile, you can test if it works on a more recent version at https://1drv.ms/f/s!AlKXEke3pNhrgYd_u4NK3tPFOY-DUA?e=Bq2oI0. These are development builds. Your issue should be solved in MuhRec-Windows_build6eeb5237-20230404.zip

**Comment by anderskaestner** [comment]
The test image is stored among my test data now.

**Comment by anderskaestner** [comment]
I just looked at the tiff header in the file you sent and could quickly identify two issues
1. The image is compressed. This is not supported as it is inefficient for reading data.
2. The images are stored as 8bit RGB. This is not supported, I'd strongly recommend changing to 16-bit unsigned integer single-channel images.

**Comment by jjpeir** [comment]
I test it with the more recent version MuhRec-Windows_build6eeb5237-20230404.zip, but it won't work. The error message is as follows
![capture20230628105128936](https://github.com/neutronimaging/imagingsuite/assets/132186720/d700e7b9-2849-4ed2-9482-ded5d6809454)

**Comment by jjpeir** [comment]
> I just looked at the tiff header in the file you sent and could quickly identify two issues
> 
> 1. The image is compressed. This is not supported as it is inefficient for reading data.
> 2. The images are stored as 8-bit RGB. This is not supported. I'd strongly recommend changing to 16-bit unsigned integer single-channel images. As this will better utilize the available dynamic range of the camera.

I check another single NR image with the more recent version MuhRec-Windows_build6eeb5237-20230404.zip.  It works.  I will check the tiff format of our automatic NCT system. Thank you very much.
![capture20230628144856564](https://github.com/neutronimaging/imagingsuite/assets/132186720/43c5249d-724b-4cbb-86fa-4c4363b56eef)
