### ISSUE TITLE
Deploy python packages

### ISSUE THREAD

**Issue by anderskaestner** [neutronimaging/imagingsuite#593]
Add python packaging to the deployment scripts

# Windows
  - [x] ImgAlg
  - [x] AdvancedFilters
  - [x] MuhRecTomo

# MacOS
  - [x] ImgAlg
  - [x] AdvancedFilters
  - [x] MuhRecTomo

# Ubuntu 
  - [x] ImgAlg
  - [x] AdvancedFilters
  - [x] MuhRecTomo

**Comment by damskii9992** [comment]
This issue appears to be closed by #666
