### ISSUE TITLE
MuhRec - crash on wrong angles when using Golden Ratio

### ISSUE THREAD

**Issue by chiaracarminati** [neutronimaging/imagingsuite#66]
MuhRec crashes when throwing this exception:

[error] MuhRec3::RunGUI: A recon exception was thrown during the main window initialization
Reconstructor exception in ../../src/ReconHelpers.cpp on line 108: 
The golden ratio reconstruction requires arc to be 180 or 360 degrees

This was experienced in Linux

**Comment by chiaracarminati** [comment]
The crash happens when opening the configure geometry dialog, otherwise don't in the main window (in this case an error message is correctly displayed)

**Comment by anderskaestner** [comment]
Quick fix: Add try catch in the slot method for configure geometry.

**Comment by anderskaestner** [comment]
This is partly prevented in the new GUI. Custom angles can't be selected with GR.

**Comment by anderskaestner** [comment]
Done
