### ISSUE TITLE
Recon exception reconstruction failure

### ISSUE THREAD

**Issue by vlocateli** [neutronimaging/imagingsuite#681]
When running to reconstruct a FITS image file i get these errors:
![error](https://github.com/neutronimaging/imagingsuite/assets/61017072/352a3c28-125a-4121-a4b3-f45a6b9e39c1)

Instructions to reproduce:
Get FITS image.
```bash
$ wget https://fits.gsfc.nasa.gov/samples/FOCx38i0101t_c0f.fits
```
Start the reconstruction.

When looking for the .so file in the directory of the error, the directory `Framework` doesn't exist, only `frameworks` followed by `tomography` sub-directory.

**Comment by anderskaestner** [comment]
@damskii9992, I think this is the same copying problem as with MacOS. Can you please update the post build copying for linux.

**Comment by damskii9992** [comment]
@anderskaestner This appear to be a path-issue rather than the copying problem. The .so file that MuhRec is looking for is properly sitting in the lib folder of the application bundle, without the "1.0.0" suffix though.
There are 3 c++ files with hard coded paths expecting a frameworks folder that shouldn't be there: "muhrecmainwindow.cpp", "modulelibnamemanger.cpp" and "tst_configbasetest.cpp" and in the modulelibnamemanger.cpp the code appends the 1.0.0 suffix to all library names . . .

**Comment by damskii9992** [comment]
A fix might be as simple as replacing the:
`fullName = fullName+"Frameworks/lib"+name+".so.1.0.0";`
on line 86 of modulelibnamemanger.cpp with:
`fullName = fullName+"lib/lib"+name+".so";`

**Comment by damskii9992** [comment]
By the way, thank you for testing out the build @vlocateli :) 
Issues like this only shows when you actually use the app, so it is greatly appreciated

**Comment by vlocateli** [comment]
I managed to fix it, now it reconstruct the FITS image. I created a branch named ` issue681_reconstructionfail`. Could @anderskaestner or @damskii9992 create this branch so I can push?  Thanks. 
![proof](https://github.com/neutronimaging/imagingsuite/assets/61017072/390c237f-b553-4fa6-92ed-42a0dfb0d13f)
:)

**Comment by damskii9992** [comment]
I have now created a branch with this name. Feel free to push your changes to it and open a pull request :)

**Comment by vlocateli** [comment]
![perm_denied](https://github.com/neutronimaging/imagingsuite/assets/61017072/1f0c7421-fe8f-4816-83f0-5a55d3c6b394)
I don't have enough permission do push to this branch. :(

**Comment by damskii9992** [comment]
@anderskaestner seems like you need to change some settings regarding access rights.

**Comment by anderskaestner** [comment]
You are now invited to the repository. Then, you should be able to push your changes. Please, only push to branches and do pull requests to merge with the main branch.
