### ISSUE TITLE
Resolution Problem with GUI (Muhrec)

### ISSUE THREAD

**Issue by vlocateli** [neutronimaging/imagingsuite#684]
If your resolution is too low, on this VM mine is (1280x720), I cannot access the bottom part, it doesn't automatically resize the window. I think if we add a sidebar might fix it.
![resolution](https://github.com/neutronimaging/imagingsuite/assets/61017072/1fe3e911-07a9-4b3e-895a-5b020c7e86eb)
As you can see from the image above, the bottom part is inaccessible. Even if I try to re-scale the window, I cannot access it. The only fix I found was changing the resolution to a higher one.

**Comment by anderskaestner** [comment]
Yes, this is a known issue and has been resolved by changing the screen for those few who needed it. I tried to make the layout more compact, but it is insufficient.

Moving all into a slider layout can be messy, but you can try. If you do it, the sliders should vanish when not needed.
