### ISSUE TITLE
Use doxygen to automate the generation of  the documentation of imagingsuite

### ISSUE THREAD

**Issue by vlocateli** [neutronimaging/imagingsuite#689]
Add doxygen to automate the generation of the documentation of the imagingsuite.
With doxygen, we can generate LaTeX files for documentation and also HTML pages.

I think doing like the warnings, opening an issue for the documentation is good so we can discuss about it.

What do you guys think? @anderskaestner @damskii9992 

I thought of this because I need to read the code to add new reconstruction algorithms.

**Comment by anderskaestner** [comment]
I have done it in some parts of the code. See e.g. core/kipl/kipl/include/base/timage.h

Go ahead...

**Comment by anderskaestner** [comment]
I should also write a tutorial on how to write new modules in the wiki
