### ISSUE TITLE
Unused variables cleanup

### ISSUE THREAD

**Issue by vlocateli** [neutronimaging/imagingsuite#694]
After doing like you told with `/* var */`, i get a compilation error like
```bash
/home/victor/Documents/git/imagingsuite/core/kipl/kipl/src/math/nonlinfit.cpp:330:9: error: no declaration matches ‘int Nonlinear::Gaussian::Hessian(double, arma::mat)’
  330 |     int Gaussian::Hessian(double x, arma::mat /*&hes*/)
      |         ^~~~~~~~
In file included from /home/victor/Documents
``` 
What do you think of using macros or C++17 way?
@anderskaestner

**Comment by vlocateli** [comment]
I used:
```c++
(void) hes;
``` to suppress this warning.
From quickly reading the code, this function isn't implemented yet. Isn't better to comment it out? I could be mistaken.
@anderskaestner

**Comment by damskii9992** [comment]
Hello Victor.
It appears that your latest commit to the master branch regarding this issue broke all the builds.
Please create branches for each issue and only push to the master branch if your branch successfully builds on all platforms :)

**Comment by vlocateli** [comment]
Hello, Christian.
On my latest pull request, i get build failure only on the Windows build.
This is the error I think:
```c++
c++.exe: warning: /openmp: linker input file unused because linking not done
c++.exe: error: /openmp: linker input file not found: No such file or directory
c++.exe: warning: /O2: linker input file unused because linking not done
c++.exe: error: /O2: linker input file not found: No such file or directory                                                                          
```
I think the program can't link with the OpenMP library.

Also, Anders said to me the rules of how to commit/contribute to the project. I thought of doing a CONTRIBUTION.md to tell instructions to other people to contribute to the project.

If I'm able to fix, I'll open another pull request. :)

**Comment by vlocateli** [comment]
So, @damskii9992. By reading the compiler output on GitHub actions webpage, I see that the compiler tries to use `\openmp when this option isn't supported by MinGW64. Isn't the path of files sometimes using `/`instead of '\' cause any troubles?
