### ISSUE TITLE
Adding utility repo to the pymuhrec package

### ISSUE THREAD

**Issue by damskii9992** [neutronimaging/imagingsuite#727]
In order to be able to run the notebooks showcasing pymuhrec, it is necessary to have the utilities from the Scripts repository https://github.com/neutronimaging/scripts. These can be added directly to the pymuhrec package under a sub-module called `utils`.

**Comment by anderskaestner** [comment]
These scripts should actually also be cleaned up and get unit tests...

**Comment by damskii9992** [comment]
Yup, which is why I already made a sub-folder with a small test for this under the tests folder :)
