### ISSUE TITLE
MuhRec - Piercing point dialog crashes

### ISSUE THREAD

**Issue by anderskaestner** [neutronimaging/imagingsuite#8]
Under unconfirmed conditions, the dialog will crash.

**Comment by anderskaestner** [comment]
It crashed in particular when a ROI is selected. Also the combination with correct gain.

**Comment by chiaracarminati** [comment]
get PP dialog is disabled in the current release (3.14)

**Comment by anderskaestner** [comment]
The estimator has now been correctly implemented and the dialog doesn't crash.
